### ISSUE TITLE
Poor error message on some rule names

### ISSUE THREAD

**Issue by nightroman** [microsoft/PSRule#1012]
# Poor error message on some rule names

If a rule name contains some characters (not supported? documented?), for example `"`,
then PSRule commands fail with cryptic messages "Illegal characters in path."
with no other details.

## Steps to reproduce and actual results

(1) Create the rule script `My.Rule.ps1`

```powershell
Rule 'My rule "1"' {
    $true
}
```

(2) Invoke

    Get-PSRule .\My.Rule.ps1
    
Result:

    Get-PSRule : Illegal characters in path.
    At line:1 char:1
    + Get-PSRule .\My.Rule.ps1
    + ~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : NotSpecified: (:) [Get-PSRule], ArgumentException
        + FullyQualifiedErrorId : System.ArgumentException,Get-PSRule

(3) Invoke

    1 | Assert-PSRule -Path .\My.Rule.ps1

Result:

    [ERROR] Illegal characters in path.

## Expected results

PSRule commands should either work or fail with clear error messages explaining which rule has not supported name.

## Version

2.0.0 Prerelease = 'B2203033'

**Comment by BernieWhite** [comment]
@nightroman Thanks for reporting this issue.

**Comment by BernieWhite** [comment]
Interestingly this is due to path validation further down the stack with Windows PowerShell 5.1 looking for help files with the same name as the rule. The issue is not present in PowerShell 7.2.

Regardless it's overdue for some validation and better guidance on rule/ resource names.

**Comment by nightroman** [comment]
@BernieWhite

> `^[a-zA-Z0-9][a-zA-Z0-9._-]{1,126}[a-zA-Z0-9]$`

I think it's a little harsh, if not plain wrong. What about names in non just English?

**Comment by BernieWhite** [comment]
@nightroman Thanks for the feedback. It warrants further thought.

**Comment by BernieWhite** [comment]
@nightroman It's not a clear as I would like, however the following regex should leave naming open without clashing with PSRule or OS specific invalid characters.

```text
^[^<>:/\\|?*\"'`+@._\-\x00-\x1F][^<>:/\\|?*\"'`+@\x00-\x1F]{1,126}[^<>:/\\|?*\"'`+@._\-\x00-\x1F]$
```

Thoughts?

**Comment by nightroman** [comment]
Thoughts are the more names allowed the better. But you should be reasonably strict to satisfy the current and potential future PSRule requirements. As for the regex, it looks reasonable but I cannot tell much without knowing exactly what the requirements are.
