### ISSUE TITLE
Geniustech

### ISSUE THREAD

**Issue by Aftabalamkhan120** [microsoft/PSRule#1021]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Aftabalamkhan120** [comment]
@Aftabalamkhan120

**Comment by BernieWhite** [comment]
@Aftabalamkhan120 We're going to need more information to be able to help. If you can complete the issue template that would help. I'm going to close the issue for now. Please resubmit when you have more information. Thanks.
