### ISSUE TITLE
Genius-Tech-1998s

### ISSUE THREAD

**Issue by Aftabalamkhan120** [microsoft/PSRule#1022]
**Description of the issue**

**To Reproduce**

Steps to reproduce the issue:

```powershell

```

**Expected behaviour**

**Error output**

```text

```

**Module in use and version:**

- Module: PSRule
- Version: **[e.g. 1.10.0]**

Captured output from `$PSVersionTable`:

```text

```

**Additional context**

**Comment by BernieWhite** [comment]
@Aftabalamkhan120 We're going to need more information to be able to help. If you can complete the issue template that would help. I'm going to close the issue for now. Please resubmit when you have more information. Thanks.
