### ISSUE TITLE
Invoking Assert-PSRule from DevOps with inline PS Script Issue

### ISSUE THREAD

**Issue by bgawale** [microsoft/PSRule#1038]
We are trying to invoke Assert-PSRule from a Powershell task in Azure DevOps. 
Our scenario is, we have bicep files stored in dedicated folders (one for each resource group) and each folder has template.bicep as main template that loads different modules. 

In order to combine template assessment using PSRule, what we are doing in DevOps pipeline is this

- Find all directories for bicep templates and iterate through template.bicep files
- Use bicep build to linter the template and save template.json file 
- Run Assert-PSRule in the same foreach for each template.parameter.json file and generate evaluation xml results
- Publish test results 

Here is gist of what we are doing in PowerShell task - https://gist.github.com/bgawale/3426d2cb0482bbbe6b88e26ab75a8f81

However upon running it - we are facing multiple errors originating from PSRule.psm1 as below

Can you confirm what is missing or if there is any better way to do it?

+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [SetOptions], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,SetOptions
 
GetSource : Cannot bind argument to parameter 'Option' because it is null.
At C:\Users\VssAdministrator\Documents\WindowsPowerShell\Modules\PSRule\2.0.0\PSRule.psm1:550 char:60
+ ... Rule.Pipeline.Source[]]$sourceFiles = GetSource @sourceParams -Verbos ...
+                                                     ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [GetSource], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,GetSource
 
The property 'Output' cannot be found on this object. Verify that the property exists.
At C:\Users\VssAdministrator\Documents\WindowsPowerShell\Modules\PSRule\2.0.0\PSRule.psm1:577 char:13
+             $Option.Output.Format = $OutputFormat;
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict
 
The property 'Output' cannot be found on this object. Verify that the property exists.
At C:\Users\VssAdministrator\Documents\WindowsPowerShell\Modules\PSRule\2.0.0\PSRule.psm1:580 char:13
+             $Option.Output.Path = $OutputPath;
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict

**Comment by BernieWhite** [comment]
@bgawale Seems like there is a bug there. What you have should work without exceptions but would return minimal results you need the `-Format File` parameter.

- PSRule automatically does a recursive search so you don't need to code that yourself. This will be much faster in general.
- Use the `-InputPath` with `-Format File`.

```powershell
Assert-PSRule -Module 'PSRule.Rules.Azure' -InputPath . -Format File -OutputPath $templateEvaluationResultFilePath -OutputFormat 'NUnit3' 
```

If you are only trying to target parameter files use: `-InputPath '**/*.parameters.json' -Format File`.
```

---
Separately PSRule for Azure will automatically build bicep files it finds. Bicep Errors will be shown in PSRule and break builds (warnings are currently ignored in PSRule).

https://azure.github.io/PSRule.Rules.Azure/using-bicep/

As of PSRule for Azure v1.13.0 it is also possible to use a metadata link using parameter files

https://azure.github.io/PSRule.Rules.Azure/using-bicep/#usingparameterfiles

```bicep
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",
    "contentVersion": "1.0.0.0",
    "metadata": {
        "template": "./template.bicep"
    },
    "parameters": {
        "storageAccountName": {
            "value": "bicepstorage001"
        },
        "tags": {
            "value": {
                "env": "test"
            }
        }
    }
}
```

For that just set the `AZURE_PARAMETER_FILE_EXPANSION` configuration option to `true`.

https://azure.github.io/PSRule.Rules.Azure/setup/configuring-expansion/#parameterfileexpansion

**Comment by bgawale** [comment]
Thanks for your response @BernieWhite - yes also tried with -Format File however the issue remained same.

**Comment by BernieWhite** [comment]
@bgawale Can you confirm you are using Windows PowerShell 5.1?

Also I suspect there may be an issue in the `ps-rule.yaml` option file. From the working path where you experience the issue can you please run `New-PSRuleOption`?

Did that fail? If so can you please provide the stack trace.
