### ISSUE TITLE
Trigger recommended action processed by rules

### ISSUE THREAD

**Issue by BernieWhite** [microsoft/PSRule#121]
Currently PSRule validates objects passed to it against a set of rules. Matching rules produce result data for reporting based on pass or failure.

PSRule can be further extended to trigger an recommended action when objects don't pass the conditions with the intent of making the object compliant.

For example:

```powershell
# Description: Use HTTPS only
Rule 'appServiceApp.UseHTTPS' -If { ResourceType 'Microsoft.Web/sites' } {
    Hint 'Disable HTTP when not required'

    $TargetObject.Properties.httpsOnly -eq $True

    Recommend -Action {
        # Corrective action
    }
}
```

```powershell
Invoke-PSRuleAction
```

**Comment by gengle** [comment]
Any consideration of using capabilities provided with https://github.com/microsoft/Requirements?

**Comment by BernieWhite** [comment]
@gengle Not at the time, as this issue was opened before it existed.

How would you see that working?

**Comment by BernieWhite** [comment]
@gengle Thanks for the suggestion, I'll have a look at this.

However any thoughts on how you would like it to work would be great.

**Comment by BernieWhite** [comment]
#322  could be used to a set block downstream to Requirements.
