### ISSUE TITLE
Bicep was not valid. Cannot cast Newtonsoft.Json.Linq.JObject to Newtonsoft.Json.Linq.JToken

### ISSUE THREAD

**Issue by Gordonby** [microsoft/PSRule#1418]
**Description of the issue**

I am encountering an issue running `PSRule.Rules.Azure` using PSRule 2.6 and 2.7 in my GitHub workflow.

> Unable to expand resources because the source file '/home/runner/work/AKS-Construction/AKS-Construction/bicep/main.bicep' was not valid. Cannot cast Newtonsoft.Json.Linq.JObject to Newtonsoft.Json.Linq.JToken.

**To Reproduce**

Use the param file https://github.com/Azure/AKS-Construction/blob/main/.github/workflows_dep/AksDeploy-ByoVnet.parameters.json

**Module in use and version:**

- Module: PSRule
- Version: **2.7.0**

**Additional context**

Workflow result : https://github.com/Azure/AKS-Construction/actions/runs/4009804697
Workflow file: https://github.com/Azure/AKS-Construction/blob/main/.github/workflows/ByoVnetCI.yml#L86
PSRule settings: https://github.com/Azure/AKS-Construction/blob/main/ps-rule.yaml

**Comment by BernieWhite** [comment]
@Gordonby Thanks for reporting the issue. Using an older version of Bicep CLI such as v0.11.x would be a temporary workaround until we fix the issue. The structure of the generated ARM code changed around this time.

**Comment by aavdberg-work** [comment]
Getting the same error now at a customer

```
Error: Unable to expand resources because the source file '/home/runner/work/iac/iac/Azure/Templates/ALZ/LandingZones/Corp/alz-ox-dwh/main/alz-ox-dwh-main.bicep' was not valid. Unable to cast object of type 'Newtonsoft.Json.Linq.JValue' to type 'Newtonsoft.Json.Linq.JObject'.
```

**Comment by aavdberg** [comment]
Getting the same error at a customer:

```
Error: Unable to expand resources because the source file '/home/runner/work/iac/iac/Azure/Templates/ALZ/LandingZones/Corp/alz-ox-dwh/main/alz-ox-dwh-main.bicep' was not valid. Unable to cast object of type 'Newtonsoft.Json.Linq.JValue' to type 'Newtonsoft.Json.Linq.JObject'.
```

**Comment by BernieWhite** [comment]
@aavdberg Can you confirm PSRule for Azure v1.24.1?

**Comment by aavdberg** [comment]
<img width="426" alt="image" src="https://user-images.githubusercontent.com/22030609/219129000-b1b44dc9-7143-4325-b069-83a952e476be.png">
