### ISSUE TITLE
Using @v2 instead of @v2.7.0

### ISSUE THREAD

**Issue by aavdberg** [microsoft/PSRule#1431]
Not related to a other problem

In other actions the `@v1` or `@v2` and so on is supported to get the latest version of a major build, but in PS Rule you have specify the full version.

So would like is when i fill in `@v2` that it will use the latest version what is 2.7.0 at the moment of writing this.

**Additional context**

**Comment by BernieWhite** [comment]
@aavdberg Thanks for the request. I like the idea.
