### ISSUE TITLE
Array output parameter from a bicep module is working during parent bicep module explansion

### ISSUE THREAD

**Issue by jegadeesan-ponnusamy** [microsoft/PSRule#1554]
**Description of the issue**
The PSRule bicep module expansion fails with the below error message for a module which takes an array input.
Failed to expand bicep source 'D:\a\1\s\GlobalTest.bicep'. Exception calling "GetBicepResources" with "2" argument(s): "Unable to expand resources because the source file 'D:\a\1\s\GlobalTest.bicep' was not valid. An error occurred evaluating expression '[length(parameters('nameServers'))]' line 879. Invalid cast from 'System.String' to 'Newtonsoft.Json.Linq.JArray'.

**To Reproduce**

We have a parent bicep module which in turn calls multiple other bicep modules (childs).  The child1 (dnszone bicep module) returns an array output parameter (i.e. nameServers). The array output is passed as an input to child 2 (dns zone delegation bicep module). When we run PSRule validation through Azure Devops pipeline using "ps-rule-assert@2" task. It fails with the error message detailed above. 

**Expected behaviour**

The module expansion should work without this error message. 

**Error output**

```text
Failed to expand bicep source 'D:\a\1\s\GlobalTest.bicep'. Exception calling "GetBicepResources" with "2" argument(s): "Unable to expand resources because the source file 'D:\a\1\s\GlobalTest.bicep' was not valid. An error occurred evaluating expression '[length(parameters('nameServers'))]' line 879. Invalid cast from 'System.String' to 'Newtonsoft.Json.Linq.JArray'.
```

**Module in use and version:**

Using PSRule v2.9.0
Using PSRule.Rules.Azure v1.27.3

Captured output from `$PSVersionTable`:

```text
> Checking module: PSRule.Rules.Azure
  - Installing module
  - Using version: 1.27.3
> Checking module: PSRule.Rules.Kubernetes
  - Installing module
  - Using version: 0.2.0
> Checking module: PSRule.Rules.CAF
  - Installing module
  - Using version: 0.3.0
```
Please let me know, if you need any additional information

**Comment by BernieWhite** [comment]
@jegadeesan-ponnusamy We believe this issue should be fixed in PSRule for Azure
v1.28.0-B0079.
