### ISSUE TITLE
$（*LIVE STREAMs*）*Montana State vs New Mexico Live Online Tv Channel 24 August 2024

### ISSUE THREAD

**Issue by SiqiSUN** [microsoft/PSRule#2014]
College football odds: FCS' Montana State opens 2024 season as historic double-digit favorite over New Mexico

If oddsmakers are right, first-year New Mexico coach Bronco Mendenhall certainly has his work cut out for him. His Lobos are 13.5-point underdogs on their home turf in Saturday's season opener against Montana State of the Football Championship Subdivision, according to the SportsLine Consensus. 

It's the largest margin for an FCS team over an FBS team in at least 15 years. It's also the first double-digit spread favoring an FCS team over an FBS team since 2013, when Jacksonville State was given a 10.5-point advantage against Georgia State. Below are the largest FCS-over-FBS lines, per CBS Sports Research: 

2024: Montana State (-13.5) vs. New Mexico
2013: Jacksonville State (-10.5) vs. Georgia State
2013  Samford (-7.5) vs. Georgia State
2018  Northern Arizona (-7) vs. UTEP
2015  Villanova (-7) vs. UConn
2014  Cal Poly (-7) vs. New Mexico State
The line has only grown in Montana State's favor since it opened at 4.5 points. Though preseason lines are hardly indicative of actual results, a win Saturday would certainly be a feather in Montana State's cap as it enters a 2024 season with FCS national championship goals. 

The Bobcats came in at No. 4 in the FCS Coaches Poll, behind the likes of South Dakota State and North Dakota State. They're also No. 3 in Emory Hunt's preseason FCS Power Rankings. They have a 32-9 record over the past three seasons under coach Brent Vigen and have finished each year with a top-10 ranking. 

Beating FBS teams isn't uncharted territory for Montana State, though it has been a while. The Bobcats beat Colorado 19-10 in 2006, their only such triumph since the turn of the century. 

New Mexico, meanwhile, has been trending in a different direction. The Lobos haven't had a winning season since 2016, when former coach Bob Davie led them to an 8-4 regular-season record capped by a win in the New Mexico Bowl. 

In four years under former coach Danny Gonzales, New Mexico was 11-32 with a 5-26 showing in Mountain West play. The Lobos have not lost to an FCS team since 2011's 48-45 overtime defeat at the hands of Sam Houston State. 

"I thought the Mendenhall hire was an A-plus-plus," said Taylor McHargue, a college football analyst for CBS Sports. "One of the better Group of Five hires this offseason, so that's the upside for New Mexico. The downside is it didn't really feel like there was a ton of talent on the team and the talent was there, some of them left and hit the portal. The challenge for New Mexico is across the board. They're not favored in any game this season

**Comment by tysonrony** [comment]
[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)

[Montana State vs New Mexico Live](http://kayotvs.store/soccer/)
