### ISSUE TITLE
Update CI pipeline to use Pester v5

### ISSUE THREAD

**Issue by BernieWhite** [microsoft/PSRule#478]
Pester v5 has just been released and introduced a number of breaking changes. These changes are not compatible with the current pipeline configuration.

For the moment Pester v4 will be used, however it should be upgraded to v5 at some time in the future.

**Comment by ArmaanMcleod** [comment]
@BernieWhite Can assign this to me. I can migrate the pester tests to v5 just like in PSRule.Rules.Azure 🙂

**Comment by BernieWhite** [comment]
@ArmaanMcleod Thanks Armaan.
