### ISSUE TITLE
Prefer module sources over loose files

### ISSUE THREAD

**Issue by BernieWhite** [microsoft/PSRule#610]
Currently when running PSRule commands from the same working directory as a loaded module, rules are returned twice. Once within the context of a module and once as a loose file.

Ideally a rule should only be returned once, preferring the module over loose files.

```powershell
Import-Module .\out\modules\PSRule
Import-Module .\tests\PSRule.Tests\TestModule
cd .\tests\PSRule.Tests\TestModule\
Get-PSRuleHelp
```

```text
Name                                ModuleName               Synopsis
----                                ----------               --------
M1.Rule1                                                     This is the default
M1.Rule2                                                     This is the default
M1.Rule1                            TestModule               Synopsis en-AU.
M1.Rule2                            TestModule               This is the default
```

This would change the expected output to only include:

```text
Name                                ModuleName               Synopsis
----                                ----------               --------
M1.Rule1                            TestModule               Synopsis en-AU.
M1.Rule2                            TestModule               This is the default
```

**Comment by ArmaanMcleod** [comment]
@BernieWhite I can take this one. 

I've also noticed this with `Get-PSRule`:

```pwsh
Import-Module .\out\modules\PSRule
Import-Module .\tests\PSRule.Tests\TestModule
cd .\tests\PSRule.Tests\TestModule\
Get-PSRuleHelp
```

Which gives:

````
RuleName                            ModuleName                 Synopsis
--------                            ----------                 --------
M1.Rule1                                                       This is the default
M1.Rule2                                                       This is the default
M1.YamlTestName                                                A YAML rule for testing
````

In this case module rules are excluded. I guess this should be consistent across all cmdlets to prefer module sources over loose ones?

**Comment by BernieWhite** [comment]
@ArmaanMcleod `Get-PSRule` requires `-ListAvailable` as it only reads rules that are in path or supplied via `-Module` by default. This is a slight difference in behaviour to make rule discovery easier when using `Get-PSRuleHelp`.

Use of loose (standalone) and module rules is often required when a customer has any custom rules such as tagging requirements etc..

I can't see any requirement that a rule should be discovered in a module then the same rule as standalone or in a different module.

I think an easy option would be to just do the module source file discovery first, then loose. As source files are being discovered only allow the file to be added once. (I think this is already done).

Secondarily, when loading rules if the same Id is loaded error, and warn if the same rule name is used.
