### ISSUE TITLE
Assertion for checking if field value doesn't exist

### ISSUE THREAD

**Issue by ArmaanMcleod** [microsoft/PSRule#775]
**Is your feature request related to a problem? Please describe.**

To check if an object property has a specific value, I use the `$Assert.HasFieldValue()` assertion.

However, there doesn't seem to be an inverted assertion to check if a value doesn't exist e.g. `$Assert.NotHasFieldValue()`. This would be helpful to detect unwanted values for certain properties. 

**Describe the solution you'd like**

A `NotHasFieldValue()` assertion to be introduced.

For example, I have to check `"availabilityZones": null` and `"availabilityZones": []` are not set in the template. The first can be easily done with `$Assert.NotNull()`, however the second one there doesn't seem to be an easy way to detect if an empty array is set. This is where `NotHasFieldValue()` would be useful, or even a `IsEmptyArray()` assertion could be used. 

**Describe alternatives you've considered**

Not sure of any assertion that could work here. Let me know if I'm missing an assertion that could work here 🙂 

**Additional context**

**Comment by ArmaanMcleod** [comment]
@BernieWhite Let me know if the above is ok to implement, I can create a PR to add those in 🙂 .

**Comment by BernieWhite** [comment]
@ArmaanMcleod Yes you can use normal PowerShell, or `$Assert.Create` as you suggest to get an `AssertResult`.

The [NullOrEmpty](https://microsoft.github.io/PSRule/concepts/PSRule/en-US/about_PSRule_Assert.html#nullorempty) assertion method would meet your requirements here if I'm not mistaken.
