### ISSUE TITLE
Add indent formatting for JSON output

### ISSUE THREAD

**Issue by BernieWhite** [microsoft/PSRule#817]
Currently JSON output from cmdlets is machine first, i.e. compact without indenting and spacing.

This is not readable easily by people without first formatting.

Add configurable options for formatting JSON output to make it more readable by default.

For example:

**Indent with 2 spaces**

```yaml
output:
  jsonIndent: 2
```

**Machine first without indenting (existing)**

```yaml
output:
  jsonIndent: 0
```

**Indent with 4 spaces**

```yaml
output:
  jsonIndent: 4
```

Related to #816

**Comment by ArmaanMcleod** [comment]
@BernieWhite I think this is a great addition. Wondering if we should also include an option to sort keys in this configuration? Or do you think all YAML/JSON configurations should sort by key always?

**Comment by BernieWhite** [comment]
@ArmaanMcleod Sure sounds fine to me, agree it should be a default. Can't see why someone might want to change that but there might be a use case for adding a configuration option such as `output.sortObjectKeys`.
