### ISSUE TITLE
Add support for JSON based resources

### ISSUE THREAD

**Issue by BernieWhite** [microsoft/PSRule#833]
Currently resources such as Baselines, Module Configurations, Rules, and Selectors can be written in YAML.

This is great and offers a good option humans to write these resources.

For some cases it would be helpful to make it easier code to automatically generate these resources. While YAML can be automated, there is much better support for this with JSON, so added JSON support for storing resource would be a good idea.

**Comment by ArmaanMcleod** [comment]
@BernieWhite Let me know what else we should cover in this issue. Happy to add more JSON support for the other resources like Module Configurations, Rules, and Selectors.

**Comment by BernieWhite** [comment]
@ArmaanMcleod For this one JSON rule and selector support would be key. This would make it easier to do https://github.com/Azure/PSRule.Rules.Azure/issues/181. Since selectors are a subset of rules enabling both should not be much additional work once rules is done.

Once rules can be written in JSON, we can work to export policies from an Azure subscription to JSON based rules.

---

Currently baselines can be formatted/ exported to JSON however they would not currently be read from JSON by the pipeline.

For example ps1 and YAML rules are pulled into PSRule via: https://github.com/microsoft/PSRule/blob/c05a7c7036f118004cfa112e2197793518a3de75/src/PSRule/Host/HostHelper.cs#L35-L41.

Other resources via: 

https://github.com/microsoft/PSRule/blob/c05a7c7036f118004cfa112e2197793518a3de75/src/PSRule/Host/HostHelper.cs#L95-L101

Sources discovered by:

https://github.com/microsoft/PSRule/blob/c05a7c7036f118004cfa112e2197793518a3de75/src/PSRule/Pipeline/SourcePipeline.cs#L334-L338

**Comment by ArmaanMcleod** [comment]
Thanks @BernieWhite. I think I'll create a `ReadJsonObjects` method and implement a JsonConverter for `ResourceObject`. Will probably have to convert this implementation: https://github.com/microsoft/PSRule/blob/main/src/PSRule/Common/YamlConverters.cs#L473. 

What do you think?

**Comment by ArmaanMcleod** [comment]
To close this out, just need to ensure module configs work with JSON. I havn't tested this, but adding some tests wouldn't hurt.

**Comment by BernieWhite** [comment]
@ArmaanMcleod Yes, should be fine module configs are the only resource not tested. Let's add tests and close. Thanks.
