### ISSUE TITLE
Add JSON support for reading rules and selectors from pipeline

### ISSUE THREAD

**Issue by ArmaanMcleod** [microsoft/PSRule#857]
Extending from #833, we can add JSON support for reading rules and selectors from pipeline. Currently they can be exported to JSON, but not read fron JSON. 

We will need to create a an equivalent `LanguageExpression` deserializer to handle parsing `if` Selector expressions, which should be similar to the YAML implementation: https://github.com/microsoft/PSRule/blob/main/src/PSRule/Common/YamlConverters.cs#L611.

**Comment by ArmaanMcleod** [comment]
@BernieWhite What do you think? I think creating a `LanguageExpression` json converter could be doable, but would probably get tricky. Do you see another more straightforward approach?

**Comment by BernieWhite** [comment]
@ArmaanMcleod Agreed.
