### ISSUE TITLE
Add NotNullOrEmpty assertion

### ISSUE THREAD

**Issue by ArmaanMcleod** [microsoft/PSRule#872]
There are times when I am creating assertions like so:

```powershell
$propNotSet = -not $Assert.NullOrEmpty($TargetObject, 'prop1').Result;
$anotherAssertion = $Assert.GreaterOrEqual($TargetObject, 'prop2', 3).Result;

$Assert.Create(
    ($propNotSet -and $anotherAssertion),
    $LocalizedData.Something,
    ...
);
```

But I would like to use `AllOf` with a collection of assertions. I cannot just pass in `NullOrEmpty` as the check needs to be inverted and I resort to using `Assert.Create` with my own AND bool condition as shown above. 

Ideally including a `NotNullOrEmpty` assertion would mean I could do:

```powershell
$Assert.AllOf(
    $Assert.NotNullOrEmpty($TargetObject, 'prop1'),
    $Assert.GreaterOrEqual($TargetObject, 'prop2', 3)
).Reason(
    $LocalizedData.Something,
    ...
);
```

Which makes things easier to work with and makes the assertion much more clearer in my opinion. 

I see we have a `NotNull` assertion. Would make sense to include a `NotNullOrEmpty` asserton as well. 

Let me know if this is something I can include or if I'm missing something with `AllOf`.

Additionally from the `AllOf` method signature:

```csharp
public AssertResult AllOf(params AssertResult[] results)
```

I can only get away with passing a collection of assertions, which makes me believe including `NotNullOrEmpty` is needed to for this to work with `AllOf`.

**Comment by BernieWhite** [comment]
@ArmaanMcleod Yes you are correct.

**Comment by ArmaanMcleod** [comment]
Closing this as this behaviour can be handled by `HasFieldValue`.
