### ISSUE TITLE
PSRule Terraform Support?

### ISSUE THREAD

**Issue by jbla9028** [microsoft/PSRule#907]
**Is your feature request related to a problem? Please describe.**
It appears that psrule can review a ARM or bicep template from the documentation. It seems like the only open to review terraform is to review the resources after the terraform code has applied the infrastructure. Can we get native terraform support?

Passing a target folder, along with variables, can psrule review a user's terraform code for compliance?

**Describe the solution you'd like**

**Describe alternatives you've considered**
There are other solutions that will do this but psRule's syntax seems very easy to use, it would be great to leverage it with terraform.

**Additional context**

**Comment by BernieWhite** [comment]
@jbla9028 Thanks for the request.

PSRule can process terraform HCL when outputted as JSON. https://www.terraform.io/internals/json-format

However I think by this request you are more talking about support for testing Azure resources from HCL code with [PSRule for Azure](https://azure.github.io/PSRule.Rules.Azure/).

If that correct?

**Comment by BernieWhite** [comment]
@jbla9028 OK thanks. No terraform plan produces an output custom and entirely different from the native Azure structure.

**Comment by BernieWhite** [comment]
@jbla9028 I don't think this is going to be a quick implementation. In theory it would be awesome, but I can imagine there may be issues mapping the terraform providers.

I'm going to transfer this issue over to PSRule for Azure, for the moment.
