### ISSUE TITLE
Add conversion property to Less/Greater expressions

### ISSUE THREAD

**Issue by ArmaanMcleod** [microsoft/PSRule#943]
Following up from #908,

The following expressions have conversion capability but currently are not exposed through the `convert` property introduced from the type expressions:

- `Less` - https://github.com/microsoft/PSRule/blob/main/src/PSRule/Definitions/Expressions/LanguageExpressions.cs#L689
- `LessOrEquals` - https://github.com/microsoft/PSRule/blob/main/src/PSRule/Definitions/Expressions/LanguageExpressions.cs#L724
- `Greater` - https://github.com/microsoft/PSRule/blob/main/src/PSRule/Definitions/Expressions/LanguageExpressions.cs#L759
- `GreaterOrEquals` - https://github.com/microsoft/PSRule/blob/main/src/PSRule/Definitions/Expressions/LanguageExpressions.cs#L794

This is configurable with the equivalent assertions.

**Comment by ArmaanMcleod** [comment]
@BernieWhite Let me know if this is needed. I noticed this while doing the PR for type expressions.

**Comment by BernieWhite** [comment]
@ArmaanMcleod Yes, we should make the expression implementation consistent with the assertions where possible.

**Comment by BernieWhite** [comment]
@ArmaanMcleod As discussed. Re-assigning this one.
