### ISSUE TITLE
Output Format

### ISSUE THREAD

**Issue by RenukaMane** [microsoft/PSRule#988]
Hello

We have tested our organization's azure resources data using PSRule locally. We wanted to know if there is a way to get the output into a JSON format so that it will be easy to ingest it into Power BI for easy reporting.

**Comment by BernieWhite** [comment]
@RenukaMane Additionally to the JSON output that @ArmaanMcleod suggested. You can also push results into Log Analytics and pull the data from Log Analytics into Power BI.

Info here: https://github.com/microsoft/PSRule.Monitor
Example here: https://azure.github.io/PSRule.Rules.Azure/setup/setup-azure-monitor-logs/

**Comment by BernieWhite** [comment]
Maybe continue this discussion/ question over here: https://github.com/microsoft/PSRule/discussions/987

**Comment by RenukaMane** [comment]
@ArmaanMcleod Thanks, it worked got the output in JSON format.

**Comment by RenukaMane** [comment]
@BernieWhite Thanks, will definitely try it out.
