### ISSUE TITLE
`Get-PSRule` - return `LineNumber` in addition to `SourcePath`

### ISSUE THREAD

**Issue by nightroman** [microsoft/PSRule#990]
Like for `Invoke-Build` build scripts and their tasks I'd like to be able to get PSRule rules with exact locations in their files, i.e. with line numbers included. Currently I can get a script as `SourcePath` and this is it, no location.

**Suggestion**

The objects returned by `Get-PSRule` should have the property `LineNumber`  (or similar) in addition to `SourcePath`. If it's applicable only for .ps1 rule files, other file rules may omit this property or provide null, 0, -1, etc.

**Why**

(1) It's a useful information in any case, e.g. for large files with many rules.

(2) I'd like to invoke the PSRule "current task" from an editor, given the known current caret line number. For `Invoke-Build` tasks this is implemented via helper tools in VSCode editor ([Invoke-TaskFromVSCode.ps1](https://github.com/nightroman/Invoke-Build/blob/master/Invoke-TaskFromVSCode.ps1)) and in the Far Manager integrated editor using the similar approach.

**Comment by BernieWhite** [comment]
@nightroman Thanks for the request. Sounds cool. I'm not sure that would work quite in the same way, since PSRule is executed in a sandbox runspace. But it sounds like it would potentially be useful in several scenarios.

**Comment by nightroman** [comment]
@BernieWhite 

> I'm not sure that would work quite in the same way, since PSRule is executed in a sandbox runspace.

Oh, this is not an obstacle at all. All we need for mentioned scenarios is to know rule source locations. Then we may start a new `powershell` or `pwsh` with properly calculated parameters depending on the context. (The bigger obstacle is how to provide an input specific for a rule. But this is secondary and doable one way or another.)

**Comment by nightroman** [comment]
Suggestion 2, I think related, but I may open another request/discussion. Objects returned by `Invoke-PSRule` have various useful details about rules but I cannot find any role source info. It would be nice to have it. I do not have any practical use cases yet but common sense and experience tell that they exist.

**Comment by BernieWhite** [comment]
@nightroman You can try this out in the latest pre-release through `Extent.File`, `Extent.Line`, `Extent.Position`. Let us know how you go.

**Comment by nightroman** [comment]
@BernieWhite Thank you, will do shortly and come back.

**Comment by nightroman** [comment]
@BernieWhite Thank you once again it's exactly what I needed. I've integrated this in Far Manager, where I can now invoke a particular (current) rule from the editor. Great ability for developing rule scripts.

**Comment by nightroman** [comment]
One question though (no pressure), when do you plan to release? (so that I can publish, too)

**Comment by BernieWhite** [comment]
@nightroman This month. But ideally sooner rather than later assuming there are not any additional bug fixes that need to be made.
